export const jobList = [
  {
    id: 1,
    companyName: "Facebook",
    jobTitle: "Senior Ract Developer",
    isRemote: true,
    jobType: "Full time",
    jobRole: "Programming",
    location: "Bangladesh",
    createdAt: "3hr ago",
    salary: "2000",
    adminId: 1,
  },
  {
    id: 2,
    companyName: "Facebook",
    jobTitle: "Senior Ract Developer",
    isRemote: true,
    jobType: "Full time",
    jobRole: "Programming",
    location: "Bangladesh",
    createdAt: "3hr ago",
    salary: "2000",
    adminId: 1,
  },
  {
    id: 3,
    companyName: "Facebook",
    jobTitle: "Senior Ract Developer",
    isRemote: true,
    jobType: "Full time",
    jobRole: "Programming",
    location: "Bangladesh",
    createdAt: "3hr ago",
    salary: "2000",
    adminId: 1,
  },
  {
    id: 4,
    companyName: "Facebook",
    jobTitle: "Senior Ract Developer",
    isRemote: true,
    jobType: "Full time",
    jobRole: "Programming",
    location: "Bangladesh",
    createdAt: "3hr ago",
    salary: "2000",
    adminId: 1,
  },
  {
    id: 5,
    companyName: "Facebook",
    jobTitle: "Senior Ract Developer",
    isRemote: true,
    jobType: "Full time",
    jobRole: "Programming",
    location: "Bangladesh",
    createdAt: "3hr ago",
    salary: "2000",
    adminId: 1,
  },
];

export const user = [];

export const admin = [];
