export const jobList = [
  {
    id: 1,
    companyName: "Meta Corporation",
    jobTitle: "Senior React Developer",
    jobType: "Full Time",
    jobRole: "Programming",
    location: "Bangladesh",
    isRemote: true,
    createdAt: "3hr ago",
    salary: "2000",
    jobApplyStatus: false,
    isFavorite: false,
    adminId: 1,
  },
  {
    id: 2,
    companyName: "Meta Corporation",
    jobTitle: "Senior React Developer",
    jobType: "Full Time",
    jobRole: "Programming",
    location: "Bangladesh",
    isRemote: true,
    createdAt: "3hr ago",
    salary: "2000",
    jobApplyStatus: false,
    isFavorite: false,
    adminId: 1,
  },
  {
    id: 3,
    companyName: "Meta Corporation",
    jobTitle: "Senior React Developer",
    jobType: "Full Time",
    jobRole: "Programming",
    location: "Bangladesh",
    isRemote: true,
    createdAt: "3hr ago",
    salary: "2000",
    jobApplyStatus: false,
    isFavorite: false,
    adminId: 1,
  },
  {
    id: 4,
    companyName: "Meta Corporation",
    jobTitle: "Senior React Developer",
    jobType: "Full Time",
    jobRole: "Programming",
    location: "Bangladesh",
    isRemote: true,
    createdAt: "3hr ago",
    salary: "2000",
    jobApplyStatus: false,
    isFavorite: false,
    adminId: 1,
  },
];

export const user = [];

export const admin = [];
